#
# Travis CI
#

sudo: false
language: php

php:
  - 5.6
  - 7.1
  - 7.3

cache:
  directories:
    - ~/.composer

install: true

before_script:
  - mkdir -p build/logs # Create a folder to store clover files
  - composer install

script:
  - vendor/bin/parallel-lint --exclude vendor/ -e php,module,inc,install,profile,theme .
  - vendor/bin/phpunit --configuration=phpunit.xml --coverage-text --coverage-clover=coverage.xml
  - vendor/bin/phpcs --ignore=vendor/ --standard=vendor/drupal/coder/coder_sniffer/Drupal/ruleset.xml --extensions=php,module,inc,install,profile,theme --report=full --warning-severity=0 .
  - vendor/bin/phpmd --exclude vendor/ --suffixes php,module,inc,install,profile,theme . text phpmd.xml

after_script:
  - travis_retry php vendor/bin/php-coveralls -v
